### ISSUE TITLE
Name of interface method

### ISSUE THREAD

**Issue by dario-campagna** [damianoravalico/Tennis-Refactoring-Kata#3]
Il nuovo nome che sostituisce getScore è sicuramente preciso. Migliora effettivamente la leggibilità del codice?

https://github.com/damianoravalico/Tennis-Refactoring-Kata/blob/7b93e6dd4a4359ade51761d8caea2e699bd1ba06/java/src/main/java/TennisGame1.java#L20

**Comment by cima22** [comment]
Abbiamo rinominato "getScore" dal momento che il nome, secondo noi, non rispecchiava appieno quello che faceva il metodo.
"getScore" sembra indicare che il valore esista già e viene solamente trovato e restituito, ma non calcolato
"buildCurrentGameResult" ci sembrava un nome più appropriato: costruisce la stringa dati i punteggi attuali dei giocatori e la restituisce, sottintendendo una logica più complessa sotto la scocca
